modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
logoFile="assets/${id}/icon.png"
credits="${authors}"
authors="${authors}"
description="${description}"
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
